import { fontHeading, fontMono, fontSans } from "@/lib/fonts/index";
import clsx from "clsx";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PoddyLinks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          fontHeading.variable,
          fontSans.variable,
          fontMono.variable,
          "font-sans antialiased",
        )}
      >
        {children}
      </body>
    </html>
  );
}
